@startuml
digraph G {
"commit baf72c" --> "tree b2ef9e"
"tree b2ef9e" --> "tree ffe156 (.idea)"
"tree ffe156 (.idea)" --> "blob 13566b (.gitignore)"
"tree ffe156 (.idea)" --> "blob 8b8c39 (2.iml)"
"tree ffe156 (.idea)" --> "blob 30bab2 (discord.xml)"
"tree ffe156 (.idea)" --> "tree 97824e (inspectionProfiles)"
"tree 97824e (inspectionProfiles)" --> "blob 105ce2 (profiles_settings.xml)"
"tree ffe156 (.idea)" --> "blob e1058f (misc.xml)"
"tree ffe156 (.idea)" --> "blob fb4f10 (modules.xml)"
"tree b2ef9e" --> "blob 500f7c (README.md)"
"tree b2ef9e" --> "blob c6c90b (config.json)"
"tree b2ef9e" --> "blob 254d53 (main.py)"
"tree b2ef9e" --> "tree 829d7a (papka)"
"tree 829d7a (papka)" --> "blob e69de2 (new_file1.txt)"
"commit baf72c" --> "commit dd0dfb"
"commit dd0dfb" --> "tree 8f352f"
"tree 8f352f" --> "tree ffe156 (.idea)"
"tree ffe156 (.idea)" --> "blob 13566b (.gitignore)"
"tree ffe156 (.idea)" --> "blob 8b8c39 (2.iml)"
"tree ffe156 (.idea)" --> "blob 30bab2 (discord.xml)"
"tree ffe156 (.idea)" --> "tree 97824e (inspectionProfiles)"
"tree 97824e (inspectionProfiles)" --> "blob 105ce2 (profiles_settings.xml)"
"tree ffe156 (.idea)" --> "blob e1058f (misc.xml)"
"tree ffe156 (.idea)" --> "blob fb4f10 (modules.xml)"
"tree 8f352f" --> "blob 500f7c (README.md)"
"tree 8f352f" --> "blob c6c90b (config.json)"
"tree 8f352f" --> "blob 254d53 (main.py)"
}
@enduml
